name: Link Check

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Checkout source branch
      - uses: gaurav-nelson/github-action-markdown-link-check@v1
        name: Check links
        with:
          use-quiet-mode: 'yes'
          use-verbose-mode: 'yes'
